version: "3.9"
services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'standings-postgres'
      POSTGRES_USER: 'standings'
      POSTGRES_PASSWORD: 'h44AkV9O@gRy'
    ports:
      - '5432:5432'
#    volumes:
#      - data:/var/lib/postgresql/data