services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "standings-db"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_standings:/data/postgres
    ports:
      - "5432:5432"
volumes:
    db_standings:
      external: true