name: Auto Assign
on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  assign-pr-ao-autor:
    runs-on: ubuntu-latest
    steps:
      - name: Atribuir PR eou Issue ao autor
        run: |
          author=`jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH`
          token=$GITHUB_TOKEN
          number=`jq -r '.pull_request.number' $GITHUB_EVENT_PATH`
          curl -s -H "Authorization: token $token" -X POST -d "{\"assignees\":[\"$author\"]}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$number/assignees"